In [1]:
import tensorflow as tf
print(tf.constant('helloe world'))

tf.Tensor(b'helloe world', shape=(), dtype=string)


In [2]:
print(tf.constant(1))

tf.Tensor(1, shape=(), dtype=int32)


In [3]:
print(tf.constant([[1,2,3,4,54],[1,2,3,4,54]]))

tf.Tensor(
[[ 1  2  3  4 54]
 [ 1  2  3  4 54]], shape=(2, 5), dtype=int32)


In [4]:
print(tf.zeros(19))

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(19,), dtype=float32)


In [5]:
print(tf.ones([10,10]))

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


In [6]:
a=tf.constant(121.5)
r1=tf.sqrt(a)
print(r1)
r3=tf.add(a,tf.constant(5.3))
print(r3)
r4=tf.multiply(tf.constant(7.3),tf.constant(5.3))
print(r4)
#with tf.session() as s:
   # print(s.run(r1))
print(r4.dtype)
print(tf.cast(r4,dtype=tf.int32).dtype)
a1=tf.cast(r4,dtype=tf.int32).dtype

tf.Tensor(11.022704, shape=(), dtype=float32)
tf.Tensor(126.8, shape=(), dtype=float32)
tf.Tensor(38.690002, shape=(), dtype=float32)
<dtype: 'float32'>
<dtype: 'int32'>


In [7]:
type(a1)

tensorflow.python.framework.dtypes.DType